# Generated by Django 5.2.6 on 2025-11-24 20:22

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="weatherlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameField(
            model_name="weatherlog",
            old_name="collected_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="weatherlog",
            old_name="raw_payload",
            new_name="raw",
        ),
        migrations.RemoveField(
            model_name="weatherlog",
            name="rain_probability",
        ),
        migrations.RemoveField(
            model_name="weatherlog",
            name="source",
        ),
        migrations.AddField(
            model_name="weatherlog",
            name="city",
            field=models.CharField(default="Brasilia", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherlog",
            name="pressure",
            field=models.FloatField(default=1013.25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherlog",
            name="timestamp",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weatherlog",
            name="condition",
            field=models.CharField(
                default="desconhecido",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weatherlog",
            name="humidity",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weatherlog",
            name="temperature",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weatherlog",
            name="wind_speed",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
